-- ════════════════════════════════════════════════════════
-- RESET COMPLETO DE PRODUTOS — Barba Lenhador
-- Apaga TODOS os produtos da Barba Lenhador e cadastra só os 97
-- da planilha de links da Yampi que você enviou.
-- ⚠️ ISSO É DESTRUTIVO — apaga tudo que já tava cadastrado antes.
-- ════════════════════════════════════════════════════════

-- 1) Apaga todos os produtos da Barba Lenhador
delete from produtos where empresa = 'Barba Lenhador';

-- 2) Insere os 97 produtos da planilha
insert into produtos (nome, link_yampi, categoria, empresa, ativo) values
  ('1 Ativador + 1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/GK3PYAKHRQ', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 Ativador de crescimento', 'https://seguro.loja-barbalenhador.com.br/pay/D8JNCVTSPQ', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 C/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/BUIGVACYA', 'Minoxidil', 'Barba Lenhador', true),
  ('1 C/ Kirkland + 1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/XXXZFPUXJG', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 C/ Kirkland + 1 Pente de Madeira + 1 Máquina de Acabamento + 1 Chapinha para Barba', 'https://seguro.loja-barbalenhador.com.br/pay/GXZK7WNNWA', 'Acessórios', 'Barba Lenhador', true),
  ('1 C/ Kirkland + 3 Multivitaminicos + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/ANU0WHARNG', 'Minoxidil', 'Barba Lenhador', true),
  ('1 C/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/GYQJFXUNWA', 'Minoxidil', 'Barba Lenhador', true),
  ('1 C/ Kirkland + Pente de Madeira', 'https://seguro.loja-barbalenhador.com.br/pay/O5OIQJYA', 'Minoxidil', 'Barba Lenhador', true),
  ('1 C/Kirkland + Hidratante', 'https://seguro.loja-barbalenhador.com.br/pay/6Z3GYVCFBW', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 Caixa de Minoxidil + 1 Multivitaminico + 1 Ativador', 'https://seguro.loja-barbalenhador.com.br/pay/GGVREWNZ6Q', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 Caixa de Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/JZJ2GSH7PQ', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Caixa Minoxidil + 1 Multivitamínico + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/VJ7SLWJ0A', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 Caixa Minoxidil + 1 Pomada major seco', 'https://seguro.loja-barbalenhador.com.br/pay/CNVLX5OK9A', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/Q2IOCENMWQ', 'Minoxidil', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Hidratante Facial', 'https://seguro.loja-barbalenhador.com.br/pay/OBWFBVMOGW', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Hidratante Facial + 1 Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/CPKEYQVVOQ', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Hidratante Facial + 1 Esfoliante Facial + 1 Multivitamínico Ativador', 'https://seguro.loja-barbalenhador.com.br/pay/DSK5QLTDBA', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/FWCUXRXDW', 'Minoxidil', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Multivitaminico + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/XWMWITPG8G', 'Minoxidil', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Pomada efeito seco', 'https://seguro.loja-barbalenhador.com.br/pay/HRYTRQGVVQ', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Pomada efeito seco + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/TWIOXQQIDA', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland + 1 Pomada efeito úmido + Derma Roller', 'https://seguro.loja-barbalenhador.com.br/pay/QSKWKWTDTQ', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland + Derma roller C/ Conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/LSL8FYPDA', 'Minoxidil', 'Barba Lenhador', true),
  ('1 F/ Kirkland + Pomada efeito úmido', 'https://seguro.loja-barbalenhador.com.br/pay/VQMUY9SSMW', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 F/ Kirkland Ativador Brinde', 'https://seguro.loja-barbalenhador.com.br/pay/CSQHUA7CRG', 'Minoxidil', 'Barba Lenhador', true),
  ('1 F/ Kirkland s/ conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/QG43WOJTIQ', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Frasco + Espuma Massageadora', 'https://seguro.loja-barbalenhador.com.br/pay/OOYAJRM6W', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 Frasco 109,90', 'https://seguro.loja-barbalenhador.com.br/pay/SWLBYWVE7W', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Frasco de Minoxidil + 1 Ativador de crescimento', 'https://seguro.loja-barbalenhador.com.br/pay/YM4TVBM7QA', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 Frasco Minoxidil + 1 Multivitamínico + 1 Pomada', 'https://seguro.loja-barbalenhador.com.br/pay/18BW6K6EA', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 Frasco Minoxidil + 1 Multivitaminico Ativador', 'https://seguro.loja-barbalenhador.com.br/pay/3EF9ROF1WA', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Frasco Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/EYSZ7O0IQ', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Hidratante + 1 Espuma massageadora', 'https://seguro.loja-barbalenhador.com.br/pay/IMOGQASYGX', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 Kit lenhador + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/U1JKSAH3W', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Minoxidil + 1 Multivitamínico', 'https://seguro.loja-barbalenhador.com.br/pay/ASASTUZPAQ', 'Minoxidil', 'Barba Lenhador', true),
  ('1 Minoxidil Foligain exclusivo', 'https://seguro.loja-barbalenhador.com.br/pay/0TJS99UW', 'Geral', 'Barba Lenhador', true),
  ('1 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/ONO7XRBAPW', 'Ativadores Major', 'Barba Lenhador', true),
  ('1 óleo + 1 Multivitamínico + 1 Pomada seco', 'https://seguro.loja-barbalenhador.com.br/pay/IMOGQASYG', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 Pomada efeito Seco', 'https://seguro.loja-barbalenhador.com.br/pay/IAXI2LALYW', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('1 Pomada Efeito Úmido', 'https://seguro.loja-barbalenhador.com.br/pay/QP0YMLY7Q', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('10 Frascos de minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/YP2NN9LAOW', 'Minoxidil', 'Barba Lenhador', true),
  ('15 Frascos Minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/XIYEYRR62G', 'Minoxidil', 'Barba Lenhador', true),
  ('2 Ativadores crescimento', 'https://seguro.loja-barbalenhador.com.br/pay/LFNNSDIAXQ', 'Ativadores Major', 'Barba Lenhador', true),
  ('2 C/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/EJBU0F4SGW', 'Minoxidil', 'Barba Lenhador', true),
  ('2 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/ACEZYT3ZOA', 'Minoxidil', 'Barba Lenhador', true),
  ('2 F/ Kirkland + 2 Multivitaminico', 'https://seguro.loja-barbalenhador.com.br/pay/MI9I05ES3A', 'Minoxidil', 'Barba Lenhador', true),
  ('2 F/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/GDLNW8QYTG', 'Ativadores Major', 'Barba Lenhador', true),
  ('2 F/ Kirkland S/ Conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/B6AKVN5YQ', 'Geral', 'Barba Lenhador', true),
  ('2 Frascos + 1 Multivitamínico + 1 Brinde', 'https://seguro.loja-barbalenhador.com.br/pay/6DIX7MGU5W', 'Ativadores Major', 'Barba Lenhador', true),
  ('2 Frascos + 2 Multivitamínicos + 1 Ativador brind', 'https://seguro.loja-barbalenhador.com.br/pay/WE07JOJKLQ', 'Ativadores Major', 'Barba Lenhador', true),
  ('2 Frascos + Ativador brinde', 'https://seguro.loja-barbalenhador.com.br/pay/F7B5J04AZG', 'Geral', 'Barba Lenhador', true),
  ('2 Frascos + Esfoliante', 'https://seguro.loja-barbalenhador.com.br/pay/8MXS0KJ0QA', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('2 Frascos Brasil', 'https://seguro.loja-barbalenhador.com.br/pay/YDRONZYOA', 'Minoxidil', 'Barba Lenhador', true),
  ('2 Frascos de Minoxidil + 1 Multivitamínco + dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/VZLKXNPP2W', 'Ativadores Major', 'Barba Lenhador', true),
  ('2 Frascos Foligain', 'https://seguro.loja-barbalenhador.com.br/pay/QISBJ4JV3Q', 'Geral', 'Barba Lenhador', true),
  ('2 Frascos Minoxidil + 2 Multivitamínico + Dermarollerr', 'https://seguro.loja-barbalenhador.com.br/pay/FC1YFARFA', 'Minoxidil', 'Barba Lenhador', true),
  ('2 Frascos Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/F9HCSM9DW', 'Minoxidil', 'Barba Lenhador', true),
  ('2 Multivitamínico Ativador MAJOR', 'https://seguro.loja-barbalenhador.com.br/pay/90QEHAKQEW', 'Ativadores Major', 'Barba Lenhador', true),
  ('2 Pomadas efeito úmido', 'https://seguro.loja-barbalenhador.com.br/pay/II8ADF7PUQ', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('3 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/NLTGOGOQWA', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland + 1 Multivitamínico', 'https://seguro.loja-barbalenhador.com.br/pay/2MKW1CVZLG', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland + 1 Pomada Efeito Seco', 'https://seguro.loja-barbalenhador.com.br/pay/7D1ANKITA', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('3 F/ Kirkland + 1 Pomada Efeito Úmido + 1 Derma roller', 'https://seguro.loja-barbalenhador.com.br/pay/SVBXMB9QG', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('3 F/ Kirkland + 2 conta-gotas', 'https://seguro.loja-barbalenhador.com.br/pay/ADEFNAIRMA', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland + 3 Multivitaminicos', 'https://seguro.loja-barbalenhador.com.br/pay/LZFEDZN4XG', 'Ativadores Major', 'Barba Lenhador', true),
  ('3 F/ Kirkland + 3 Multivitaminicos + 2 Hidratantes', 'https://seguro.loja-barbalenhador.com.br/pay/C4CLUHHEDW', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('3 F/ Kirkland + Ativador Multivitamínico (Brinde) + 1 Pomada Efeito Seco', 'https://seguro.loja-barbalenhador.com.br/pay/CEXOMYS7IQ', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/VLPFDILRG', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland + Pente de madeiras', 'https://seguro.loja-barbalenhador.com.br/pay/JR2XZQTNRQ', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland C/ Conta-Gotas + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/NAVJ1NMQFA', 'Minoxidil', 'Barba Lenhador', true),
  ('3 F/ Kirkland S/ Conta-Gotas', 'https://seguro.loja-barbalenhador.com.br/pay/BUOJCBFR9A', 'Minoxidil', 'Barba Lenhador', true),
  ('3 Frascos + 1 Ativador (Brinde)', 'https://seguro.loja-barbalenhador.com.br/pay/MJEIBYWHA', 'Minoxidil', 'Barba Lenhador', true),
  ('3 Frascos + 2 Multivitamínicos + 1 Multivitamínico brinde', 'https://seguro.loja-barbalenhador.com.br/pay/EC1RLFBYW', 'Ativadores Major', 'Barba Lenhador', true),
  ('3 FRASCOS + 3 MULTIVITAMÍNICOS + 1 DERMA ROLLER', 'https://seguro.loja-barbalenhador.com.br/pay/OZPGYNM4YG', 'Minoxidil', 'Barba Lenhador', true),
  ('3 Frascos + Esfoliante + ativador brinde', 'https://seguro.loja-barbalenhador.com.br/pay/EK4PJRGXPW', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('3 Frascos de Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/XG7JTHYZG', 'Minoxidil', 'Barba Lenhador', true),
  ('3 Frascos FG', 'https://seguro.loja-barbalenhador.com.br/pay/LVG2IHLG', 'Minoxidil', 'Barba Lenhador', true),
  ('3 Frascos Minox + 2 Multivitamínicos + 1 Ativador + 1 Multivitamínico Brinde', 'https://seguro.loja-barbalenhador.com.br/pay/SA7PNJHLA', 'Ativadores Major', 'Barba Lenhador', true),
  ('3 Multivitamínicos + 1 Esfoliante + 1 Hidratante + 1 Ativador tópico', 'https://seguro.loja-barbalenhador.com.br/pay/PJJQGEYACG', 'Ativadores Major', 'Barba Lenhador', true),
  ('4 frascos + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/B9UAB8IYA', 'Minoxidil', 'Barba Lenhador', true),
  ('4 Frascos de Minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/RWQH4ULQTG', 'Minoxidil', 'Barba Lenhador', true),
  ('4 Frascos Minoxidil + 2 Ativadores', 'https://seguro.loja-barbalenhador.com.br/pay/5YPZXUBQYW', 'Ativadores Major', 'Barba Lenhador', true),
  ('5 caixas', 'https://seguro.loja-barbalenhador.com.br/pay/3JN0DZANSG', 'Minoxidil', 'Barba Lenhador', true),
  ('5 F/ Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/C8COVZGCZA', 'Geral', 'Barba Lenhador', true),
  ('8 Frascos de Kirkland', 'https://seguro.loja-barbalenhador.com.br/pay/0T4EWAKKDA', 'Minoxidil', 'Barba Lenhador', true),
  ('9 F/ Kirkland + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/CQNBNX1TTA', 'Minoxidil', 'Barba Lenhador', true),
  ('Caixa Minoxidil + 1 Ativador brinde', 'https://seguro.loja-barbalenhador.com.br/pay/TOHCTY8EZW', 'Minoxidil', 'Barba Lenhador', true),
  ('Caixa Minoxidil + 1 Dermaroller + Pente de madeira', 'https://seguro.loja-barbalenhador.com.br/pay/EVSOY1OMAW', 'Minoxidil', 'Barba Lenhador', true),
  ('Caixa Minoxidil + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/BWQTQVTWPQ', 'Minoxidil', 'Barba Lenhador', true),
  ('Chapinha para Barba', 'https://seguro.loja-barbalenhador.com.br/pay/KP7HA6JQQG', 'Acessórios', 'Barba Lenhador', true),
  ('Kit Lenhador', 'https://seguro.loja-barbalenhador.com.br/pay/ACDUG1SAJG', 'Minoxidil', 'Barba Lenhador', true),
  ('Kit lenhador + Dermaroller', 'https://seguro.loja-barbalenhador.com.br/pay/0ZBE2RWUG', 'Minoxidil', 'Barba Lenhador', true),
  ('Kit Lenhador + Pomada efeito úmido', 'https://seguro.loja-barbalenhador.com.br/pay/DJPR0HMVA', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('Kit Premium + Minoxidil', 'https://seguro.loja-barbalenhador.com.br/pay/ZD6KGHVU5W', 'Major - Linha Completa', 'Barba Lenhador', true),
  ('Máquina de acabamento', 'https://seguro.loja-barbalenhador.com.br/pay/SWOZWUP6SW', 'Acessórios', 'Barba Lenhador', true),
  ('Óleo para Barba e Cabelo Major', 'https://seguro.loja-barbalenhador.com.br/pay/DAPZQAW', 'Geral', 'Barba Lenhador', true),
  ('Sérum Anti-Oleosidade MAJOR', 'https://seguro.loja-barbalenhador.com.br/pay/QQVMEXYVQQ', 'Major - Linha Completa', 'Barba Lenhador', true);

-- 3) Confere o total (deve dar exatamente 97)
select count(*) as total_produtos from produtos where empresa = 'Barba Lenhador';